### ISSUE TITLE
Line under H1 not showing

### ISSUE THREAD

**Issue by eduardo-w-bandeira** [Bluemoondragon07/Wikipedia-Theme#2]
Hi. Here's a screenshot of my Obsidian 1.1.16 using your theme:
![image](https://user-images.githubusercontent.com/78479953/229542121-72344c2e-4885-4c1b-b094-342228127599.png)

It seems that Obsidian is not rendering the theme correctly. Do you happen to know why the bottom border is not showing in Heading 1?

**Comment by Bluemoondragon07** [comment]
Hi. Sorry about the rendering issue. I am not sure why the border is not visible in this instance, but I am aware that it does disappear in edit mode (in the screenshot, it appears that you are in reading mode, though). I think it's because I only put the styles under `h1` instead of something more specific, like `.markdown-rendered h1`. I apologize for this theme being so messy--when I made it, I didn't know css and was just messing around.  I am currently redoing this theme from scratch, though, so rendering problems will soon be fixed.

**Comment by Bluemoondragon07** [comment]
I'll also let you know when I update the theme to the new version.

**Comment by eduardo-w-bandeira** [comment]
Don't be sorry. It's not a big deal. I just wanted to understand why the CSS wasn't working. And you're right, I was in editing mode, but if I change it to reading mode, the lines show up. Thank you.

**Comment by Bluemoondragon07** [comment]
Just finished remaking the theme last night, and I fixed the rendering issue. Please update to the newest version.
